export const columns = [
  {
    title: 'Tên',
    dataIndex: 'name',
    key: 'name',
    width: 400,
    resizable: true,
    sorter: (a: any, b: any) => a.name.localeCompare(b.name),
    sortDirections: ['ascend', 'descend'],
  },
  {
    title: 'Giá',
    dataIndex: 'price',
    key: 'price',
    width: 150,
    resizable: true,
    sorter: (a: any, b: any) => a.price - b.price,
    sortDirections: ['ascend', 'descend'],
  },
  {
    title: 'Số lượng',
    dataIndex: 'amount',
    key: 'amount',
    width: 150,
    resizable: true,
    sorter: (a: any, b: any) => a.amount - b.amount,
    sortDirections: ['ascend', 'descend'],
  },
  {
    title: 'Đã bán',
    dataIndex: 'sold',
    key: 'sold',
    width: 150,
    resizable: true,
    sorter: (a: any, b: any) => a.sold - b.sold,
    sortDirections: ['ascend', 'descend'],
  },
  {
    title: 'Sale',
    dataIndex: 'isSale',
    key: 'isSale',
    width: 150,
    resizable: true,
  },
]
