export const getColumns = (t: (key: string) => string) => [
  {
    title: t('adminProducts.columnProduct'),
    dataIndex: 'name',
    key: 'name',
    width: 360,
    resizable: true,
    sorter: (a: any, b: any) => a.name.localeCompare(b.name),
    sortDirections: ['ascend', 'descend'],
  },
  {
    title: t('adminProducts.columnPrice'),
    dataIndex: 'price',
    key: 'price',
    width: 150,
    resizable: true,
    sorter: (a: any, b: any) => a.price - b.price,
    sortDirections: ['ascend', 'descend'],
  },
  {
    title: t('adminProducts.columnQuantity'),
    dataIndex: 'amount',
    key: 'amount',
    width: 150,
    resizable: true,
    sorter: (a: any, b: any) => a.amount - b.amount,
    sortDirections: ['ascend', 'descend'],
  },
  {
    title: t('adminProducts.columnSold'),
    dataIndex: 'sold',
    key: 'sold',
    width: 150,
    resizable: true,
    sorter: (a: any, b: any) => a.sold - b.sold,
    sortDirections: ['ascend', 'descend'],
  },
  {
    title: t('adminProducts.columnSale'),
    dataIndex: 'isSale',
    key: 'isSale',
    width: 150,
    resizable: true,
  },
  {
    title: t('adminProducts.columnAction'),
    key: 'action',
    width: 96,
    fixed: 'right',
  },
]
