export const columns = [
  {
    title: 'Mã đơn hàng',
    dataIndex: 'orderCode',
    key: 'orderCode',
    width: 200,
    resizable: true,
  },
  {
    title: 'Tên khách hàng',
    dataIndex: 'customerName',
    key: 'customerName',
    width: 200,
    resizable: true,
  },
  {
    title: 'Số điện thoại',
    dataIndex: 'phoneNumber',
    key: 'phoneNumber',
    width: 150,
    resizable: true,
  },
  {
    title: 'Tổng tiền',
    dataIndex: 'totalPrice',
    key: 'totalPrice',
    width: 150,
    resizable: true,
  },
  {
    title: 'Phuong thức thanh toán',
    dataIndex: 'paymentMethod',
    key: 'paymentMethod',
    width: 200,
    resizable: true,
    filters: [
      { text: 'Thanh toán khi nhận hàng', value: 'CASH' },
      { text: 'Thanh toán online', value: 'CARD' },
    ],
    onFilter: (value: string, record: any) => record.paymentMethod === value,
  },
  {
    title: 'Trạng thái',
    dataIndex: 'status',
    key: 'status',
    width: 150,
    resizable: true,
    filters: [
      { text: 'Đang chờ', value: 'PENDING' },
      { text: 'Đã xác nhận', value: 'CONFIRM' },
      { text: 'Đang giao hàng', value: 'DELIVERY' },
      { text: 'Đã hoàn thành', value: 'COMPLETE' },
      { text: 'Đã hủy', value: 'CANCEL' },
    ],
    onFilter: (value: string, record: any) => record.status === value,
    filterMultiple: true,
  },
  {
    title: 'Cập nhật trạng thái',
    key: 'action',
    width: 200,
    resizable: true,
  },
]
